<?php
session_start();

// Check if user is logged in and is admin
if (!isset($_SESSION['logged_in']) || !$_SESSION['logged_in']) {
    header('Location: login.php');
    exit();
}

if ($_SESSION['user_type'] !== 'admin') {
    header('Location: customer_dashboard.php');
    exit();
}

$admin_name = $_SESSION['full_name'];
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Stocks - Dimi's Donuts</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="update_stocks.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <style>
        * {
            font-family: 'Poppins', sans-serif;
        }

        body {
            background: linear-gradient(135deg, #FFF5F7 0%, #FFE4EC 100%);
            min-height: 100vh;
        }

        /* Make SweetAlert2 appear above everything */
        .swal2-container {
            z-index: 30000 !important;
        }

        .navbar {
            background: linear-gradient(135deg, #FF6B8B 0%, #FF8FA3 100%);
            box-shadow: 0 4px 20px rgba(255, 107, 139, 0.3);
            padding: 1rem 0;
        }

        .navbar-brand {
            font-weight: 700;
            font-size: 1.5rem;
            color: white !important;
        }

        .nav-link {
            color: rgba(255, 255, 255, 0.9) !important;
            font-weight: 500;
            margin: 0 0.5rem;
            transition: all 0.3s ease;
        }

        .nav-link:hover,
        .nav-link.active {
            color: white !important;
            transform: translateY(-2px);
        }

        .page-header {
            background: white;
            padding: 2rem 0;
            margin-bottom: 2rem;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        }

        .page-title {
            font-weight: 700;
            color: #333;
            margin: 0;
        }
    </style>
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="admin_dashboard.php">
                <i class="bi bi-shop"></i> Dimi's Donuts Admin
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="admin_dashboard.php">
                            <i class="bi bi-speedometer2"></i> Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="update_stocks.php">
                            <i class="bi bi-box-seam"></i> Inventory
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="view_reports.php">
                            <i class="bi bi-graph-up"></i> Reports
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" id="logoutLink">
                            <i class="bi bi-box-arrow-right"></i> Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <div class="page-header">
        <div class="container">
            <h1 class="page-title">
                <i class="bi bi-box-seam"></i> Inventory Management
            </h1>
        </div>
    </div>

    <!-- Main Content -->
    <div class="container">
        <div class="mb-3">
            <button class="btn btn-success" id="addProductBtn">
                <i class="fas fa-plus"></i> Add New Product
            </button>
        </div>
        <div class="stocks-grid" id="stocksGrid">
            <!-- Stock cards will be generated by JavaScript -->
        </div>
    </div>

    <!-- Low Stock Notification -->
    <div id="lowStockNotification" class="low-stock-notification">
        <div class="notification-icon">
            <i class="fas fa-exclamation-triangle"></i>
        </div>
        <div class="notification-content">
            <div class="notification-title">Low Stock Alert</div>
            <p class="notification-message" id="notificationMessage">Some products are running low on stock.</p>
        </div>
        <button class="notification-close" id="closeNotification">
            <i class="fas fa-times"></i>
        </button>
    </div>

    <!-- Product Dialog -->
    <div id="productDialog" class="product-dialog">
        <div class="product-dialog-content">
            <div class="product-dialog-header">
                <button class="product-dialog-close" id="productDialogClose">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="product-dialog-body">
                <div class="dialog-ingredients-section">
                    <h3 class="section-title">Ingredients needed:</h3>
                    <div class="ingredients-table-container">
                        <table class="ingredients-table" id="dialogIngredientsTable">
                            <thead>
                                <tr>
                                    <th>Ingredient</th>
                                    <th>Quantity</th>
                                    <th>Unit</th>
                                    <th>Unit Cost</th>
                                    <th>Total Cost</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Ingredients will be populated by JavaScript -->
                            </tbody>
                        </table>
                        <button class="add-ingredient-to-product-btn" id="addIngredientToProductBtn">
                            <i class="fas fa-plus"></i> Add Ingredient
                        </button>
                    </div>
                </div>

                <div class="dialog-product-section">
                    <div class="product-price">
                        <h3 id="dialogDonutName">Product Name</h3>
                        <div class="price" id="dialogDonutPrice">₱0</div>
                    </div>

                    <div class="product-description">
                        <h4>DESCRIPTION</h4>
                        <p id="dialogDonutDescription">Product description</p>
                    </div>

                    <div class="ingredients-cost">
                        <h4>INGREDIENTS TOTAL COST</h4>
                        <div class="cost-value" id="dialogIngredientsCost">₱0</div>
                    </div>

                    <div class="stock-update-section">
                        <div class="stock-update-info">
                            <span class="stock-update-label">Current Stock</span>
                            <span class="stock-update-value" id="dialogCurrentStock">0</span>
                        </div>

                        <div class="stock-update-change">
                            <button class="change-btn decrease-btn" id="dialogDecreaseBtn">-</button>
                            <span class="stock-update-change-display" id="dialogChangeDisplay">+0</span>
                            <button class="change-btn increase-btn" id="dialogIncreaseBtn">+</button>
                        </div>

                        <button class="stock-update-btn" id="dialogUpdateBtn">UPDATE STOCK</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Add/Edit Ingredient Modal -->
    <div id="ingredientModal" class="ingredient-modal" style="display: none;">
        <div class="ingredient-modal-content">
            <div class="ingredient-modal-header">
                <h3 id="ingredientModalTitle">Add Ingredient</h3>
                <button class="ingredient-modal-close" id="ingredientModalClose">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="ingredient-modal-body">
                <div class="form-group">
                    <label for="ingredientSelect">Select Ingredient</label>
                    <select id="ingredientSelect" class="form-control">
                        <option value="">-- Select Ingredient --</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="ingredientQuantity">Quantity Needed</label>
                    <input type="number" id="ingredientQuantity" class="form-control" step="0.01" min="0">
                </div>
                <div class="ingredient-info" id="ingredientInfo" style="display: none;">
                    <p><strong>Unit:</strong> <span id="ingredientUnit">-</span></p>
                    <p><strong>Unit Cost:</strong> ₱<span id="ingredientUnitCost">0.00</span></p>
                    <p><strong>Available Stock:</strong> <span id="ingredientStock">0</span></p>
                </div>
            </div>
            <div class="ingredient-modal-footer">
                <button class="btn btn-secondary" id="ingredientCancelBtn">Cancel</button>
                <button class="btn btn-primary" id="ingredientSaveBtn">Save</button>
            </div>
        </div>
    </div>

    <!-- Add Product Modal -->
    <div id="addProductModal" class="product-dialog" style="display: none;">
        <div class="product-dialog-content">
            <div class="product-dialog-header">
                <h2>Add New Product</h2>
                <button class="product-dialog-close" id="addProductClose">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="product-dialog-body">
                <div class="dialog-ingredients-section">
                    <h3 class="section-title">Ingredients</h3>
                    <div class="ingredients-table-container">
                        <table class="ingredients-table" id="newProductIngredientsTable">
                            <thead>
                                <tr>
                                    <th>Ingredient</th>
                                    <th>Quantity</th>
                                    <th>Unit</th>
                                    <th>Unit Cost</th>
                                    <th>Total Cost</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Ingredients will be populated by JavaScript -->
                            </tbody>
                        </table>
                        <button class="add-ingredient-to-product-btn" id="addIngredientToNewProductBtn">
                            <i class="fas fa-plus"></i> Add Ingredient
                        </button>
                    </div>
                </div>

                <div class="dialog-product-section">
                    <div class="product-form">
                        <div class="form-group">
                            <label for="newProductName">Product Name</label>
                            <input type="text" id="newProductName" class="form-control"
                                placeholder="Enter product name">
                        </div>

                        <div class="form-group">
                            <label for="newProductCode">Product Code</label>
                            <input type="text" id="newProductCode" class="form-control" placeholder="e.g., A1, B2">
                        </div>

                        <div class="form-group">
                            <label for="newProductCategory">Category</label>
                            <select id="newProductCategory" class="form-control">
                                <option value="donut_tray">Donut Tray</option>
                                <option value="donut_tower">Donut Tower</option>
                                <option value="donut_wall">Donut Wall</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="newProductPrice">Price (₱)</label>
                            <input type="number" id="newProductPrice" class="form-control" placeholder="0.00" min="0"
                                step="0.01">
                        </div>

                        <div class="form-group">
                            <label for="newProductFlavor">Flavor</label>
                            <input type="text" id="newProductFlavor" class="form-control"
                                placeholder="e.g., Chocolate, Strawberry, Vanilla">
                        </div>

                        <div class="form-group">
                            <label for="newProductDescription">Description</label>
                            <textarea id="newProductDescription" class="form-control"
                                placeholder="Enter product description" rows="4"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="newProductImage">Product Image</label>
                            <input type="file" id="newProductImage" class="form-control" accept="image/*">
                            <small class="form-text text-muted">Upload a product image (JPG, PNG)</small>
                        </div>

                        <div class="form-group">
                            <label for="newProductStock">Initial Stock</label>
                            <input type="number" id="newProductStock" class="form-control" placeholder="0" min="0"
                                value="0">
                        </div>

                        <div class="form-group">
                            <label for="newProductMaxStock">Maximum Stock</label>
                            <input type="number" id="newProductMaxStock" class="form-control" placeholder="50" min="1"
                                value="50">
                        </div>

                        <div class="ingredients-cost">
                            <h4>INGREDIENTS TOTAL COST</h4>
                            <div class="cost-value" id="newProductIngredientsCost">₱0.00</div>
                        </div>

                        <button class="stock-update-btn" id="saveNewProductBtn">SAVE PRODUCT</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Product Modal -->
    <div id="editProductModal" class="product-dialog" style="display: none;">
        <div class="product-dialog-content">
            <div class="product-dialog-header">
                <h2>Edit Product</h2>
                <button class="product-dialog-close" id="editProductClose">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="product-dialog-body">
                <div class="dialog-ingredients-section">
                    <h3 class="section-title">Ingredients</h3>
                    <div class="ingredients-table-container">
                        <table class="ingredients-table" id="editProductIngredientsTable">
                            <thead>
                                <tr>
                                    <th>Ingredient</th>
                                    <th>Quantity</th>
                                    <th>Unit</th>
                                    <th>Unit Cost</th>
                                    <th>Total Cost</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Ingredients will be populated by JavaScript -->
                            </tbody>
                        </table>
                        <button class="add-ingredient-to-product-btn" id="addIngredientToEditProductBtn">
                            <i class="fas fa-plus"></i> Add Ingredient
                        </button>
                    </div>
                </div>

                <div class="dialog-product-section">
                    <div class="product-form">
                        <input type="hidden" id="editProductId">

                        <div class="form-group">
                            <label for="editProductName">Product Name</label>
                            <input type="text" id="editProductName" class="form-control"
                                placeholder="Enter product name">
                        </div>

                        <div class="form-group">
                            <label for="editProductCode">Product Code</label>
                            <input type="text" id="editProductCode" class="form-control" placeholder="e.g., A1, B2">
                        </div>

                        <div class="form-group">
                            <label for="editProductCategory">Category</label>
                            <select id="editProductCategory" class="form-control">
                                <option value="donut_tray">Donut Tray</option>
                                <option value="donut_tower">Donut Tower</option>
                                <option value="donut_wall">Donut Wall</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="editProductPrice">Price (₱)</label>
                            <input type="number" id="editProductPrice" class="form-control" placeholder="0.00" min="0"
                                step="0.01">
                        </div>

                        <div class="form-group">
                            <label for="editProductFlavor">Flavor</label>
                            <input type="text" id="editProductFlavor" class="form-control"
                                placeholder="e.g., Chocolate, Strawberry, Vanilla">
                        </div>

                        <div class="form-group">
                            <label for="editProductDescription">Description</label>
                            <textarea id="editProductDescription" class="form-control"
                                placeholder="Enter product description" rows="4"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="editProductImage">Product Image</label>
                            <input type="file" id="editProductImage" class="form-control" accept="image/*">
                            <small class="form-text text-muted">Upload a new image or leave empty to keep
                                current</small>
                            <div id="currentImagePreview" style="margin-top: 10px;"></div>
                        </div>

                        <div class="form-group">
                            <label for="editProductMaxStock">Maximum Stock</label>
                            <input type="number" id="editProductMaxStock" class="form-control" placeholder="50" min="1"
                                value="50">
                        </div>

                        <div class="ingredients-cost">
                            <h4>INGREDIENTS TOTAL COST</h4>
                            <div class="cost-value" id="editProductIngredientsCost">₱0.00</div>
                        </div>

                        <button class="stock-update-btn" id="updateProductBtn">UPDATE PRODUCT</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const API_BASE = 'api';
        let currentProductId = null;
        let currentStockChange = 0;
        let allProducts = [];
        let allIngredients = [];
        let currentProductIngredients = [];
        let newProductIngredients = [];

        // Load all ingredients from database
        async function loadAllIngredients() {
            try {
                const response = await fetch(`${API_BASE}/products/get_all_ingredients.php`);
                if (!response.ok) throw new Error('Failed to load ingredients');
                const data = await response.json();
                if (data.success) {
                    allIngredients = data.data.ingredients;
                    populateIngredientSelect();
                }
            } catch (error) {
                console.error('Error loading ingredients:', error);
            }
        }

        // Populate ingredient dropdown
        function populateIngredientSelect() {
            const select = document.getElementById('ingredientSelect');
            select.innerHTML = '<option value="">-- Select Ingredient --</option>';
            allIngredients.forEach(ing => {
                const option = document.createElement('option');
                option.value = ing.ingredient_id;
                option.textContent = `${ing.ingredient_name} (${ing.unit})`;
                option.dataset.unit = ing.unit;
                option.dataset.unitCost = ing.unit_cost;
                option.dataset.stock = ing.stock_quantity;
                select.appendChild(option);
            });
        }

        // Show ingredient info when selected
        document.getElementById('ingredientSelect').addEventListener('change', function() {
            const selectedOption = this.options[this.selectedIndex];
            if (this.value) {
                document.getElementById('ingredientUnit').textContent = selectedOption.dataset.unit;
                document.getElementById('ingredientUnitCost').textContent = parseFloat(selectedOption.dataset
                    .unitCost).toFixed(2);
                document.getElementById('ingredientStock').textContent = selectedOption.dataset.stock;
                document.getElementById('ingredientInfo').style.display = 'block';
            } else {
                document.getElementById('ingredientInfo').style.display = 'none';
            }
        });

        // Load products
        async function loadProducts() {
            try {
                // Add cache-busting parameter and large limit to get all products
                const response = await fetch(`${API_BASE}/products/list.php?limit=1000&_=${Date.now()}`);
                if (!response.ok) throw new Error('Failed to load products');
                const data = await response.json();
                console.log('Products loaded:', data);
                if (data.success) {
                    allProducts = data.data.products;
                    console.log('Total products:', allProducts.length);
                    renderProductCards();
                    checkLowStock();
                }
            } catch (error) {
                console.error('Error loading products:', error);
                Swal.fire('Error', 'Failed to load products', 'error');
            }
        }

        // Render product cards
        function renderProductCards() {
            const grid = document.getElementById('stocksGrid');
            grid.innerHTML = '';

            allProducts.forEach(product => {
                const stockPercentage = (product.stock_quantity / (product.max_stock || 50)) * 100;
                let stockStatus = 'normal';
                let badgeClass = 'badge-normal';
                let badgeText = 'Normal';

                if (product.stock_quantity === 0) {
                    stockStatus = 'out-of-stock';
                    badgeClass = 'badge-critical';
                    badgeText = 'Out of Stock';
                } else if (product.stock_quantity < 5) {
                    stockStatus = 'critical-stock';
                    badgeClass = 'badge-critical';
                    badgeText = 'Critical';
                } else if (product.stock_quantity < 10) {
                    stockStatus = 'low-stock';
                    badgeClass = 'badge-low';
                    badgeText = 'Low Stock';
                }

                const card = document.createElement('div');
                card.className = `stock-card ${stockStatus}`;
                card.dataset.productId = product.product_id;
                card.innerHTML = `
                    <button class="product-edit-btn" onclick="event.stopPropagation(); openEditProductModal(${product.product_id})">
                        <i class="fas fa-edit"></i>
                    </button>
                    <button class="product-delete-btn" onclick="event.stopPropagation(); deleteProduct(${product.product_id}, '${product.product_name}')">
                        <i class="fas fa-trash"></i>
                    </button>
                    <div class="stock-header">
                        <h4 class="stock-title">${product.product_name}</h4>
                        <span class="stock-badge ${badgeClass}">${badgeText}</span>
                    </div>
                    <div class="stock-image">
                        ${product.image_path ? `<img src="${product.image_path}" alt="${product.product_name}" style="width:100%;height:100%;object-fit:cover;">` : product.product_name}
                    </div>
                    <div class="stock-info">
                        <span class="stock-label">Stock Level</span>
                        <span class="stock-value ${stockStatus}">${product.stock_quantity}/${product.max_stock || 50}</span>
                    </div>
                    <div class="stock-progress">
                        <div class="stock-progress-bar progress-${stockStatus}" style="width: ${Math.min(stockPercentage, 100)}%"></div>
                    </div>
                    <div class="stock-footer">
                        <span class="stock-price">₱${parseFloat(product.price).toFixed(2)}</span>
                    </div>
                `;
                card.addEventListener('click', () => openProductDialog(product.product_id));
                grid.appendChild(card);
            });
        }

        // Open product dialog
        async function openProductDialog(productId) {
            currentProductId = productId;
            currentStockChange = 0;

            const product = allProducts.find(p => p.product_id === productId);
            if (!product) return;

            // Set product info
            document.getElementById('dialogDonutName').textContent = product.product_name;
            document.getElementById('dialogDonutPrice').textContent = `₱${parseFloat(product.price).toFixed(2)}`;
            document.getElementById('dialogDonutDescription').textContent = product.description ||
                'No description available';
            document.getElementById('dialogCurrentStock').textContent = product.stock_quantity;
            document.getElementById('dialogChangeDisplay').textContent = '+0';

            // Load product ingredients
            await loadProductIngredients(productId);

            // Show dialog
            document.getElementById('productDialog').classList.add('active');
        }

        // Load product ingredients
        async function loadProductIngredients(productId) {
            try {
                const response = await fetch(
                    `${API_BASE}/products/get_ingredients_relational.php?product_id=${productId}`);
                if (!response.ok) throw new Error('Failed to load ingredients');
                const data = await response.json();

                if (data.success) {
                    currentProductIngredients = data.data.ingredients;
                    const totalCost = data.data.total_cost;

                    // Update ingredients table
                    const tbody = document.querySelector('#dialogIngredientsTable tbody');
                    tbody.innerHTML = '';

                    if (currentProductIngredients.length === 0) {
                        tbody.innerHTML =
                            '<tr><td colspan="6" style="text-align:center;">No ingredients added yet</td></tr>';
                    } else {
                        currentProductIngredients.forEach(ing => {
                            const row = document.createElement('tr');
                            row.innerHTML = `
                                <td>${ing.ingredient_name}</td>
                                <td>${parseFloat(ing.quantity_needed).toFixed(2)}</td>
                                <td>${ing.unit}</td>
                                <td>₱${parseFloat(ing.unit_cost).toFixed(2)}</td>
                                <td>₱${parseFloat(ing.total_cost).toFixed(2)}</td>
                                <td>
                                    <button class="btn-small btn-danger" onclick="removeIngredient(${ing.product_ingredient_id})">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </td>
                            `;
                            tbody.appendChild(row);
                        });
                    }

                    // Update total cost
                    document.getElementById('dialogIngredientsCost').textContent =
                        `₱${parseFloat(totalCost).toFixed(2)}`;
                }
            } catch (error) {
                console.error('Error loading product ingredients:', error);
            }
        }

        // Add ingredient to product
        document.getElementById('addIngredientToProductBtn').addEventListener('click', () => {
            document.getElementById('ingredientModal').style.display = 'flex';
            document.getElementById('ingredientModalTitle').textContent = 'Add Ingredient';
            document.getElementById('ingredientSelect').value = '';
            document.getElementById('ingredientQuantity').value = '';
            document.getElementById('ingredientInfo').style.display = 'none';
            document.getElementById('ingredientSaveBtn').setAttribute('data-mode', 'existing-product');
        });

        // Close ingredient modal
        document.getElementById('ingredientModalClose').addEventListener('click', () => {
            document.getElementById('ingredientModal').style.display = 'none';
        });

        document.getElementById('ingredientCancelBtn').addEventListener('click', () => {
            document.getElementById('ingredientModal').style.display = 'none';
        });

        // Save ingredient
        document.getElementById('ingredientSaveBtn').addEventListener('click', async () => {
            const ingredientId = document.getElementById('ingredientSelect').value;
            const quantity = document.getElementById('ingredientQuantity').value;
            const mode = document.getElementById('ingredientSaveBtn').getAttribute('data-mode') ||
                'existing-product';

            if (!ingredientId || !quantity || quantity <= 0) {
                Swal.fire('Error', 'Please select an ingredient and enter a valid quantity', 'error');
                return;
            }

            if (mode === 'new-product') {
                // Add to new product ingredients array
                const ingredient = allIngredients.find(i => i.ingredient_id == ingredientId);
                if (!ingredient) return;

                // Check if already added
                if (newProductIngredients.find(i => i.ingredient_id == ingredientId)) {
                    Swal.fire('Error', 'This ingredient is already added', 'error');
                    return;
                }

                newProductIngredients.push({
                    ingredient_id: ingredientId,
                    ingredient_name: ingredient.ingredient_name,
                    quantity_needed: quantity,
                    unit: ingredient.unit,
                    unit_cost: ingredient.unit_cost,
                    total_cost: quantity * ingredient.unit_cost
                });

                // Update table
                const tbody = document.querySelector('#newProductIngredientsTable tbody');
                tbody.innerHTML = '';
                let totalCost = 0;

                newProductIngredients.forEach((ing, index) => {
                    totalCost += parseFloat(ing.total_cost);
                    const row = document.createElement('tr');
                    row.innerHTML = `
                        <td>${ing.ingredient_name}</td>
                        <td>${parseFloat(ing.quantity_needed).toFixed(2)}</td>
                        <td>${ing.unit}</td>
                        <td>₱${parseFloat(ing.unit_cost).toFixed(2)}</td>
                        <td>₱${parseFloat(ing.total_cost).toFixed(2)}</td>
                        <td>
                            <button class="btn-small btn-danger" onclick="removeNewProductIngredient(${index})">
                                <i class="fas fa-trash"></i>
                            </button>
                        </td>
                    `;
                    tbody.appendChild(row);
                });

                document.getElementById('newProductIngredientsCost').textContent = `₱${totalCost.toFixed(2)}`;
                document.getElementById('ingredientModal').style.display = 'none';

            } else if (mode === 'edit-product') {
                // Edit product mode - add to existing product
                try {
                    const productId = document.getElementById('editProductId').value;
                    const response = await fetch(`${API_BASE}/products/add_product_ingredient.php`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            product_id: productId,
                            ingredient_id: ingredientId,
                            quantity_needed: quantity
                        })
                    });

                    const data = await response.json();
                    if (data.success) {
                        Swal.fire('Success', 'Ingredient added successfully', 'success');
                        document.getElementById('ingredientModal').style.display = 'none';
                        await loadEditProductIngredients(productId);
                    } else {
                        throw new Error(data.message || 'Failed to add ingredient');
                    }
                } catch (error) {
                    Swal.fire('Error', error.message, 'error');
                }

            } else {
                // Existing product mode (view product dialog)
                try {
                    const response = await fetch(`${API_BASE}/products/add_product_ingredient.php`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            product_id: currentProductId,
                            ingredient_id: ingredientId,
                            quantity_needed: quantity
                        })
                    });

                    const data = await response.json();
                    if (data.success) {
                        Swal.fire('Success', 'Ingredient added successfully', 'success');
                        document.getElementById('ingredientModal').style.display = 'none';
                        await loadProductIngredients(currentProductId);
                    } else {
                        throw new Error(data.message || 'Failed to add ingredient');
                    }
                } catch (error) {
                    Swal.fire('Error', error.message, 'error');
                }
            }
        });

        // Remove ingredient from new product
        window.removeNewProductIngredient = function(index) {
            newProductIngredients.splice(index, 1);

            // Update table
            const tbody = document.querySelector('#newProductIngredientsTable tbody');
            tbody.innerHTML = '';

            if (newProductIngredients.length === 0) {
                tbody.innerHTML = '<tr><td colspan="6" style="text-align:center;">No ingredients added yet</td></tr>';
                document.getElementById('newProductIngredientsCost').textContent = '₱0.00';
                return;
            }

            let totalCost = 0;
            newProductIngredients.forEach((ing, idx) => {
                totalCost += parseFloat(ing.total_cost);
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td>${ing.ingredient_name}</td>
                    <td>${parseFloat(ing.quantity_needed).toFixed(2)}</td>
                    <td>${ing.unit}</td>
                    <td>₱${parseFloat(ing.unit_cost).toFixed(2)}</td>
                    <td>₱${parseFloat(ing.total_cost).toFixed(2)}</td>
                    <td>
                        <button class="btn-small btn-danger" onclick="removeNewProductIngredient(${idx})">
                            <i class="fas fa-trash"></i>
                        </button>
                    </td>
                `;
                tbody.appendChild(row);
            });

            document.getElementById('newProductIngredientsCost').textContent = `₱${totalCost.toFixed(2)}`;
        };

        // Remove ingredient
        async function removeIngredient(productIngredientId) {
            const result = await Swal.fire({
                title: 'Remove ingredient?',
                text: 'This will remove the ingredient from this product',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, remove it',
                cancelButtonText: 'Cancel'
            });

            if (result.isConfirmed) {
                try {
                    const response = await fetch(`${API_BASE}/products/remove_product_ingredient.php`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            product_ingredient_id: productIngredientId
                        })
                    });

                    const data = await response.json();
                    if (data.success) {
                        Swal.fire('Removed!', 'Ingredient has been removed', 'success');
                        await loadProductIngredients(currentProductId);
                    } else {
                        throw new Error(data.message || 'Failed to remove ingredient');
                    }
                } catch (error) {
                    Swal.fire('Error', error.message, 'error');
                }
            }
        }

        // Stock update controls
        document.getElementById('dialogDecreaseBtn').addEventListener('click', () => {
            if (currentStockChange > -10) {
                currentStockChange--;
                document.getElementById('dialogChangeDisplay').textContent = currentStockChange >= 0 ?
                    `+${currentStockChange}` : currentStockChange;
            }
        });

        document.getElementById('dialogIncreaseBtn').addEventListener('click', () => {
            if (currentStockChange < 50) {
                currentStockChange++;
                document.getElementById('dialogChangeDisplay').textContent = currentStockChange >= 0 ?
                    `+${currentStockChange}` : currentStockChange;
            }
        });

        // Update stock
        document.getElementById('dialogUpdateBtn').addEventListener('click', async () => {
            if (currentStockChange === 0) {
                Swal.fire('Info', 'Please adjust the stock quantity', 'info');
                return;
            }

            const product = allProducts.find(p => p.product_id === currentProductId);
            const newStock = product.stock_quantity + currentStockChange;

            if (newStock < 0) {
                Swal.fire('Error', 'Stock cannot be negative', 'error');
                return;
            }

            try {
                const response = await fetch(`${API_BASE}/products/update_stock.php`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        product_id: currentProductId,
                        stock_quantity: newStock
                    })
                });

                const data = await response.json();
                if (data.success) {
                    Swal.fire('Success!', 'Stock updated successfully', 'success');
                    document.getElementById('productDialog').classList.remove('active');
                    await loadProducts();
                } else {
                    throw new Error(data.message || 'Failed to update stock');
                }
            } catch (error) {
                Swal.fire('Error', error.message, 'error');
            }
        });

        // Close product dialog
        document.getElementById('productDialogClose').addEventListener('click', () => {
            document.getElementById('productDialog').classList.remove('active');
        });

        // Check low stock
        function checkLowStock() {
            const lowStockProducts = allProducts.filter(p => p.stock_quantity < 5);

            if (lowStockProducts.length > 0) {
                const names = lowStockProducts.map(p => p.product_name).join(', ');
                document.getElementById('notificationMessage').textContent =
                    `${lowStockProducts.length} product(s) are low on stock: ${names}`;
                document.getElementById('lowStockNotification').classList.add('active');

                setTimeout(() => {
                    document.getElementById('lowStockNotification').classList.remove('active');
                }, 10000);
            }
        }

        // Close notification
        document.getElementById('closeNotification').addEventListener('click', () => {
            document.getElementById('lowStockNotification').classList.remove('active');
        });

        // Open Edit Product Modal
        window.openEditProductModal = async function(productId) {
            const product = allProducts.find(p => p.product_id === productId);
            if (!product) return;

            document.getElementById('editProductId').value = product.product_id;
            document.getElementById('editProductName').value = product.product_name;
            document.getElementById('editProductCode').value = product.product_code;
            document.getElementById('editProductCategory').value = product.category;
            document.getElementById('editProductPrice').value = product.price;
            document.getElementById('editProductFlavor').value = product.flavor || '';
            document.getElementById('editProductDescription').value = product.description || '';
            document.getElementById('editProductMaxStock').value = product.max_stock || 50;

            // Show current image
            if (product.image_path) {
                document.getElementById('currentImagePreview').innerHTML = `
                    <img src="${product.image_path}" alt="Current Image" style="max-width: 200px; border-radius: 8px;">
                `;
            } else {
                document.getElementById('currentImagePreview').innerHTML = '';
            }

            // Load product ingredients for editing
            await loadEditProductIngredients(productId);

            document.getElementById('editProductModal').style.display = 'flex';
        };

        // Load ingredients for edit product modal
        async function loadEditProductIngredients(productId) {
            try {
                const response = await fetch(
                    `${API_BASE}/products/get_ingredients_relational.php?product_id=${productId}`);
                if (!response.ok) throw new Error('Failed to load ingredients');
                const data = await response.json();

                if (data.success) {
                    const ingredients = data.data.ingredients;
                    const totalCost = data.data.total_cost;

                    const tbody = document.querySelector('#editProductIngredientsTable tbody');
                    tbody.innerHTML = '';

                    if (ingredients.length === 0) {
                        tbody.innerHTML =
                            '<tr><td colspan="6" style="text-align:center;">No ingredients added yet</td></tr>';
                    } else {
                        ingredients.forEach(ing => {
                            const row = document.createElement('tr');
                            row.innerHTML = `
                                <td>${ing.ingredient_name}</td>
                                <td>${parseFloat(ing.quantity_needed).toFixed(2)}</td>
                                <td>${ing.unit}</td>
                                <td>₱${parseFloat(ing.unit_cost).toFixed(2)}</td>
                                <td>₱${parseFloat(ing.total_cost).toFixed(2)}</td>
                                <td>
                                    <button class="btn-small btn-danger" onclick="removeEditProductIngredient(${ing.product_ingredient_id})">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </td>
                            `;
                            tbody.appendChild(row);
                        });
                    }

                    document.getElementById('editProductIngredientsCost').textContent =
                        `₱${parseFloat(totalCost).toFixed(2)}`;
                }
            } catch (error) {
                console.error('Error loading edit product ingredients:', error);
            }
        }

        // Close Edit Product Modal
        document.getElementById('editProductClose').addEventListener('click', () => {
            document.getElementById('editProductModal').style.display = 'none';
        });

        // Add ingredient to edit product
        document.getElementById('addIngredientToEditProductBtn').addEventListener('click', () => {
            document.getElementById('ingredientModal').style.display = 'flex';
            document.getElementById('ingredientModalTitle').textContent = 'Add Ingredient';
            document.getElementById('ingredientSelect').value = '';
            document.getElementById('ingredientQuantity').value = '';
            document.getElementById('ingredientInfo').style.display = 'none';
            document.getElementById('ingredientSaveBtn').setAttribute('data-mode', 'edit-product');
        });

        // Remove ingredient from edit product
        window.removeEditProductIngredient = async function(productIngredientId) {
            const result = await Swal.fire({
                title: 'Remove ingredient?',
                text: 'This will remove the ingredient from this product',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, remove it',
                cancelButtonText: 'Cancel'
            });

            if (result.isConfirmed) {
                try {
                    const response = await fetch(`${API_BASE}/products/remove_product_ingredient.php`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            product_ingredient_id: productIngredientId
                        })
                    });

                    const data = await response.json();
                    if (data.success) {
                        Swal.fire('Removed!', 'Ingredient has been removed', 'success');
                        const productId = document.getElementById('editProductId').value;
                        await loadEditProductIngredients(productId);
                    } else {
                        throw new Error(data.message || 'Failed to remove ingredient');
                    }
                } catch (error) {
                    Swal.fire('Error', error.message, 'error');
                }
            }
        };

        // Update Product
        document.getElementById('updateProductBtn').addEventListener('click', async () => {
            const productId = document.getElementById('editProductId').value;
            const name = document.getElementById('editProductName').value.trim();
            const code = document.getElementById('editProductCode').value.trim();
            const category = document.getElementById('editProductCategory').value;
            const price = document.getElementById('editProductPrice').value;
            const flavor = document.getElementById('editProductFlavor').value.trim();
            const description = document.getElementById('editProductDescription').value.trim();
            const maxStock = document.getElementById('editProductMaxStock').value;

            if (!name || !code || !price || !description) {
                Swal.fire('Error', 'Please fill in all required fields', 'error');
                return;
            }

            try {
                // Update product
                const productData = {
                    product_id: productId,
                    product_code: code,
                    product_name: name,
                    category: category,
                    price: price,
                    flavor: flavor,
                    description: description,
                    max_stock: maxStock
                };

                const response = await fetch(`${API_BASE}/products/update.php`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(productData)
                });

                const data = await response.json();
                if (data.success) {
                    // Handle image upload if provided
                    const imageFile = document.getElementById('editProductImage').files[0];
                    if (imageFile) {
                        const formData = new FormData();
                        formData.append('product_id', productId);
                        formData.append('image', imageFile);

                        await fetch(`${API_BASE}/products/upload_image.php`, {
                            method: 'POST',
                            body: formData
                        });
                    }

                    Swal.fire('Success!', 'Product updated successfully', 'success');
                    document.getElementById('editProductModal').style.display = 'none';
                    await loadProducts();
                } else {
                    throw new Error(data.message || 'Failed to update product');
                }
            } catch (error) {
                Swal.fire('Error', error.message, 'error');
            }
        });

        // Add Product Modal
        document.getElementById('addProductBtn').addEventListener('click', () => {
            newProductIngredients = [];
            document.getElementById('newProductName').value = '';
            document.getElementById('newProductCode').value = '';
            document.getElementById('newProductCategory').value = 'donut_tray';
            document.getElementById('newProductPrice').value = '';
            document.getElementById('newProductFlavor').value = '';
            document.getElementById('newProductDescription').value = '';
            document.getElementById('newProductStock').value = '0';
            document.getElementById('newProductMaxStock').value = '50';
            document.getElementById('newProductIngredientsCost').textContent = '₱0.00';
            document.querySelector('#newProductIngredientsTable tbody').innerHTML =
                '<tr><td colspan="6" style="text-align:center;">No ingredients added yet</td></tr>';
            document.getElementById('addProductModal').style.display = 'flex';
        });

        document.getElementById('addProductClose').addEventListener('click', () => {
            document.getElementById('addProductModal').style.display = 'none';
        });

        document.getElementById('addIngredientToNewProductBtn').addEventListener('click', () => {
            document.getElementById('ingredientModal').style.display = 'flex';
            document.getElementById('ingredientModalTitle').textContent = 'Add Ingredient to New Product';
            document.getElementById('ingredientSelect').value = '';
            document.getElementById('ingredientQuantity').value = '';
            document.getElementById('ingredientInfo').style.display = 'none';
            document.getElementById('ingredientSaveBtn').setAttribute('data-mode', 'new-product');
        });

        // Save New Product
        document.getElementById('saveNewProductBtn').addEventListener('click', async () => {
            const name = document.getElementById('newProductName').value.trim();
            const code = document.getElementById('newProductCode').value.trim();
            const category = document.getElementById('newProductCategory').value;
            const price = document.getElementById('newProductPrice').value;
            const flavor = document.getElementById('newProductFlavor').value.trim();
            const description = document.getElementById('newProductDescription').value.trim();
            const stock = document.getElementById('newProductStock').value;
            const maxStock = document.getElementById('newProductMaxStock').value;

            if (!name || !code || !price || !description) {
                Swal.fire('Error', 'Please fill in all required fields', 'error');
                return;
            }

            if (newProductIngredients.length === 0) {
                const result = await Swal.fire({
                    title: 'No Ingredients',
                    text: 'Do you want to create a product without ingredients?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, create it'
                });
                if (!result.isConfirmed) return;
            }

            try {
                // Create product first
                const productData = {
                    product_code: code,
                    product_name: name,
                    category: category,
                    price: price,
                    flavor: flavor,
                    description: description,
                    stock_quantity: stock,
                    max_stock: maxStock
                };

                const response = await fetch(`${API_BASE}/products/create.php`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(productData)
                });

                const data = await response.json();
                if (!data.success) {
                    throw new Error(data.message || 'Failed to create product');
                }

                const newProductId = data.product_id;
                let errors = [];

                // Upload image if provided
                const imageFile = document.getElementById('newProductImage').files[0];
                if (imageFile) {
                    try {
                        const formData = new FormData();
                        formData.append('product_id', newProductId);
                        formData.append('image', imageFile);

                        const imgResponse = await fetch(`${API_BASE}/products/upload_image.php`, {
                            method: 'POST',
                            body: formData
                        });
                        const imgData = await imgResponse.json();
                        if (!imgData.success) {
                            errors.push('Image upload failed: ' + imgData.message);
                        }
                    } catch (error) {
                        errors.push('Image upload error: ' + error.message);
                    }
                }

                // Add ingredients if any
                if (newProductIngredients.length > 0) {
                    for (const ing of newProductIngredients) {
                        try {
                            const ingResponse = await fetch(`${API_BASE}/products/add_product_ingredient.php`, {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json'
                                },
                                body: JSON.stringify({
                                    product_id: newProductId,
                                    ingredient_id: ing.ingredient_id,
                                    quantity_needed: ing.quantity_needed
                                })
                            });
                            const ingData = await ingResponse.json();
                            if (!ingData.success) {
                                errors.push('Failed to add ingredient: ' + ingData.message);
                            }
                        } catch (error) {
                            errors.push('Ingredient error: ' + error.message);
                        }
                    }
                }

                // Show result
                if (errors.length > 0) {
                    Swal.fire('Partial Success', 'Product created but some issues occurred:\n' + errors.join(
                        '\n'), 'warning');
                } else {
                    Swal.fire('Success!', 'Product created successfully', 'success');
                }

                // Close modal and reset form
                document.getElementById('addProductModal').style.display = 'none';
                document.getElementById('newProductName').value = '';
                document.getElementById('newProductCode').value = '';
                document.getElementById('newProductPrice').value = '';
                document.getElementById('newProductFlavor').value = '';
                document.getElementById('newProductDescription').value = '';
                document.getElementById('newProductImage').value = '';
                document.getElementById('newProductStock').value = '0';
                document.getElementById('newProductMaxStock').value = '50';
                newProductIngredients = [];
                document.getElementById('newProductIngredientsTable').querySelector('tbody').innerHTML = '';
                document.getElementById('newProductIngredientsCost').textContent = '₱0.00';

                // Reload products
                await loadProducts();
            } catch (error) {
                Swal.fire('Error', error.message, 'error');
            }
        });

        // Close notification
        document.getElementById('closeNotification').addEventListener('click', () => {
            document.getElementById('lowStockNotification').classList.remove('active');
        });

        // Logout
        document.getElementById('logoutLink').addEventListener('click', async (e) => {
            e.preventDefault();
            const result = await Swal.fire({
                title: 'Logout?',
                text: 'Are you sure you want to logout?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Yes, logout',
                confirmButtonColor: '#FF6B8B'
            });

            if (result.isConfirmed) {
                window.location.href = 'logout.php';
            }
        });

        // Delete Product
        window.deleteProduct = async function(productId, productName) {
            const result = await Swal.fire({
                title: 'Delete Product?',
                text: `Are you sure you want to delete "${productName}"? This action cannot be undone.`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it',
                cancelButtonText: 'Cancel',
                confirmButtonColor: '#dc3545',
                cancelButtonColor: '#6c757d'
            });

            if (result.isConfirmed) {
                try {
                    const response = await fetch(`${API_BASE}/products/delete.php`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            product_id: productId
                        })
                    });

                    const data = await response.json();
                    if (data.success) {
                        Swal.fire('Deleted!', 'Product has been deleted successfully', 'success');
                        await loadProducts();
                    } else {
                        throw new Error(data.message || 'Failed to delete product');
                    }
                } catch (error) {
                    Swal.fire('Error', error.message, 'error');
                }
            }
        };

        // Initialize
        document.addEventListener('DOMContentLoaded', async () => {
            await loadAllIngredients();
            await loadProducts();
        });
    </script>
</body>

</html>